"""likes comments and reposts

Three tables rather than one polymorphic "reaction", because they behave
differently in every way that matters: a like is a toggle with no content, a
comment is moderated free text that can be withdrawn, and a repost carries a
note. One table would need every column nullable and every query to remember
which kind it was reading.

The three counts on `catalog.experiences` are denormalised on purpose - a feed
renders dozens of cards and each shows all three, so counting per card is the
N+1 the card loader exists to avoid. They are written only by
`explorer/social.py`, and recomputed from the rows rather than incremented, so a
lost request cannot leave a count permanently wrong.

Every existing listing starts at zero, which is true.

Revision ID: 04d314e08690
Revises: 4afd88bcbe06
Create Date: 2026-08-19 18:37:42.183750
"""
from __future__ import annotations

from collections.abc import Sequence

# Custom column types autogenerate can emit. Imported unconditionally because the
# render hooks that would otherwise add them do not fire in every case - notably
# geoalchemy2 columns wrapped in sa.Computed.
import geoalchemy2  # noqa: F401
import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from alembic import op


revision: str = '04d314e08690'
down_revision: str | None = '4afd88bcbe06'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='approved', nullable=False),
    sa.Column('moderation_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['experience_id'], ['catalog.experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='explorer'
    )
    op.create_index('ix_comments_experience_created', 'comments', ['experience_id', 'created_at'], unique=False, schema='explorer')
    op.create_index(op.f('ix_explorer_comments_experience_id'), 'comments', ['experience_id'], unique=False, schema='explorer')
    op.create_index(op.f('ix_explorer_comments_user_id'), 'comments', ['user_id'], unique=False, schema='explorer')
    op.create_table('likes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['catalog.experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'experience_id', name='uq_like_user_experience'),
    schema='explorer'
    )
    op.create_index(op.f('ix_explorer_likes_experience_id'), 'likes', ['experience_id'], unique=False, schema='explorer')
    op.create_index(op.f('ix_explorer_likes_user_id'), 'likes', ['user_id'], unique=False, schema='explorer')
    op.create_index('ix_likes_experience', 'likes', ['experience_id'], unique=False, schema='explorer')
    op.create_table('reposts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['catalog.experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'experience_id', name='uq_repost_user_experience'),
    schema='explorer'
    )
    op.create_index(op.f('ix_explorer_reposts_experience_id'), 'reposts', ['experience_id'], unique=False, schema='explorer')
    op.create_index(op.f('ix_explorer_reposts_user_id'), 'reposts', ['user_id'], unique=False, schema='explorer')
    op.create_index('ix_reposts_experience', 'reposts', ['experience_id'], unique=False, schema='explorer')
    op.create_index('ix_reposts_user_created', 'reposts', ['user_id', 'created_at'], unique=False, schema='explorer')
    op.add_column('experiences', sa.Column('like_count', sa.Integer(), server_default='0', nullable=False), schema='catalog')
    op.add_column('experiences', sa.Column('comment_count', sa.Integer(), server_default='0', nullable=False), schema='catalog')
    op.add_column('experiences', sa.Column('repost_count', sa.Integer(), server_default='0', nullable=False), schema='catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiences', 'repost_count', schema='catalog')
    op.drop_column('experiences', 'comment_count', schema='catalog')
    op.drop_column('experiences', 'like_count', schema='catalog')
    op.drop_index('ix_reposts_user_created', table_name='reposts', schema='explorer')
    op.drop_index('ix_reposts_experience', table_name='reposts', schema='explorer')
    op.drop_index(op.f('ix_explorer_reposts_user_id'), table_name='reposts', schema='explorer')
    op.drop_index(op.f('ix_explorer_reposts_experience_id'), table_name='reposts', schema='explorer')
    op.drop_table('reposts', schema='explorer')
    op.drop_index('ix_likes_experience', table_name='likes', schema='explorer')
    op.drop_index(op.f('ix_explorer_likes_user_id'), table_name='likes', schema='explorer')
    op.drop_index(op.f('ix_explorer_likes_experience_id'), table_name='likes', schema='explorer')
    op.drop_table('likes', schema='explorer')
    op.drop_index(op.f('ix_explorer_comments_user_id'), table_name='comments', schema='explorer')
    op.drop_index(op.f('ix_explorer_comments_experience_id'), table_name='comments', schema='explorer')
    op.drop_index('ix_comments_experience_created', table_name='comments', schema='explorer')
    op.drop_table('comments', schema='explorer')
    # ### end Alembic commands ###
