"""publisher verification fields

Revision ID: 240ef37c5b56
Revises: 59790d37425e
Create Date: 2026-08-07 22:49:37.124116
"""
from __future__ import annotations

from collections.abc import Sequence

# Custom column types autogenerate can emit. Imported unconditionally because the
# render hooks that would otherwise add them do not fire in every case - notably
# geoalchemy2 columns wrapped in sa.Computed.
import geoalchemy2  # noqa: F401
import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from alembic import op


revision: str = '240ef37c5b56'
down_revision: str | None = '59790d37425e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publishers', sa.Column('verification_note', sa.Text(), nullable=True), schema='publisher')
    op.add_column('publishers', sa.Column('verification_requested_at', sa.DateTime(timezone=True), nullable=True), schema='publisher')
    op.add_column('publishers', sa.Column('verification_decided_at', sa.DateTime(timezone=True), nullable=True), schema='publisher')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publishers', 'verification_decided_at', schema='publisher')
    op.drop_column('publishers', 'verification_requested_at', schema='publisher')
    op.drop_column('publishers', 'verification_note', schema='publisher')
    # ### end Alembic commands ###
