"""collections

Revision ID: 27fa1e8ac939
Revises: d71f3c5e493b
Create Date: 2026-08-08 07:36:06.763388
"""
from __future__ import annotations

from collections.abc import Sequence

# Custom column types autogenerate can emit. Imported unconditionally because the
# render hooks that would otherwise add them do not fire in every case - notably
# geoalchemy2 columns wrapped in sa.Computed.
import geoalchemy2  # noqa: F401
import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from alembic import op


revision: str = '27fa1e8ac939'
down_revision: str | None = 'd71f3c5e493b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('city_slug', sa.String(length=120), nullable=True),
    sa.Column('visibility', sa.String(length=16), server_default='private', nullable=False),
    sa.Column('source', sa.String(length=16), server_default='user', nullable=False),
    sa.Column('moderation_status', sa.String(length=16), server_default='approved', nullable=False),
    sa.Column('moderation_notes', sa.Text(), nullable=True),
    sa.Column('report_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='explorer'
    )
    op.create_index('ix_collections_user', 'collections', ['user_id', 'created_at'], unique=False, schema='explorer')
    op.create_index('ix_collections_visibility', 'collections', ['visibility', 'moderation_status'], unique=False, schema='explorer')
    op.create_index(op.f('ix_explorer_collections_city_slug'), 'collections', ['city_slug'], unique=False, schema='explorer')
    op.create_index(op.f('ix_explorer_collections_slug'), 'collections', ['slug'], unique=True, schema='explorer')
    op.create_index(op.f('ix_explorer_collections_user_id'), 'collections', ['user_id'], unique=False, schema='explorer')
    op.create_table('collection_items',
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['explorer.collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['experience_id'], ['catalog.experiences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'experience_id', name='uq_collection_item'),
    schema='explorer'
    )
    op.create_index('ix_collection_items_collection', 'collection_items', ['collection_id', 'position'], unique=False, schema='explorer')
    op.create_index(op.f('ix_explorer_collection_items_experience_id'), 'collection_items', ['experience_id'], unique=False, schema='explorer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_explorer_collection_items_experience_id'), table_name='collection_items', schema='explorer')
    op.drop_index('ix_collection_items_collection', table_name='collection_items', schema='explorer')
    op.drop_table('collection_items', schema='explorer')
    op.drop_index(op.f('ix_explorer_collections_user_id'), table_name='collections', schema='explorer')
    op.drop_index(op.f('ix_explorer_collections_slug'), table_name='collections', schema='explorer')
    op.drop_index(op.f('ix_explorer_collections_city_slug'), table_name='collections', schema='explorer')
    op.drop_index('ix_collections_visibility', table_name='collections', schema='explorer')
    op.drop_index('ix_collections_user', table_name='collections', schema='explorer')
    op.drop_table('collections', schema='explorer')
    # ### end Alembic commands ###
