"""remove likes and comments

Reviews already do this job. A review is a rating and a written opinion, one per
person per listing, weighted by verified attendance and feeding the listing's
average. A like is a weaker version of the rating and a comment is a weaker
version of the opinion - so carrying both meant two places to say the same
thing, two things to moderate, and a reader having to look in two places to
learn what people thought.

`explorer.reposts` stays. A repost says "other people should see this", which a
review does not say and cannot.

**This drops data.** Any likes and comments written while the feature existed go
with the tables, and the downgrade recreates the tables empty rather than
pretending otherwise. That is acceptable here because the feature was added and
withdrawn in the same development cycle and nothing in production ever wrote to
it; if that ever stops being true, move the rows somewhere first.

Revision ID: 2b52eb5c077a
Revises: 04d314e08690
Create Date: 2026-08-19 21:51:28.334138
"""
from __future__ import annotations

from collections.abc import Sequence

# Custom column types autogenerate can emit. Imported unconditionally because the
# render hooks that would otherwise add them do not fire in every case - notably
# geoalchemy2 columns wrapped in sa.Computed.
import geoalchemy2  # noqa: F401
import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '2b52eb5c077a'
down_revision: str | None = '04d314e08690'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_experience_created'), table_name='comments', schema='explorer')
    op.drop_index(op.f('ix_explorer_comments_experience_id'), table_name='comments', schema='explorer')
    op.drop_index(op.f('ix_explorer_comments_user_id'), table_name='comments', schema='explorer')
    op.drop_table('comments', schema='explorer')
    op.drop_index(op.f('ix_explorer_likes_experience_id'), table_name='likes', schema='explorer')
    op.drop_index(op.f('ix_explorer_likes_user_id'), table_name='likes', schema='explorer')
    op.drop_index(op.f('ix_likes_experience'), table_name='likes', schema='explorer')
    op.drop_table('likes', schema='explorer')
    op.drop_column('experiences', 'comment_count', schema='catalog')
    op.drop_column('experiences', 'like_count', schema='catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiences', sa.Column('like_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False), schema='catalog')
    op.add_column('experiences', sa.Column('comment_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False), schema='catalog')
    op.create_table('likes',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('experience_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['catalog.experiences.id'], name=op.f('likes_experience_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], name=op.f('likes_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('likes_pkey')),
    sa.UniqueConstraint('user_id', 'experience_id', name=op.f('uq_like_user_experience'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='explorer'
    )
    op.create_index(op.f('ix_likes_experience'), 'likes', ['experience_id'], unique=False, schema='explorer')
    op.create_index(op.f('ix_explorer_likes_user_id'), 'likes', ['user_id'], unique=False, schema='explorer')
    op.create_index(op.f('ix_explorer_likes_experience_id'), 'likes', ['experience_id'], unique=False, schema='explorer')
    op.create_table('comments',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('experience_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), server_default=sa.text("'approved'::character varying"), autoincrement=False, nullable=False),
    sa.Column('moderation_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['experience_id'], ['catalog.experiences.id'], name=op.f('comments_experience_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], name=op.f('comments_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('comments_pkey')),
    schema='explorer'
    )
    op.create_index(op.f('ix_explorer_comments_user_id'), 'comments', ['user_id'], unique=False, schema='explorer')
    op.create_index(op.f('ix_explorer_comments_experience_id'), 'comments', ['experience_id'], unique=False, schema='explorer')
    op.create_index(op.f('ix_comments_experience_created'), 'comments', ['experience_id', 'created_at'], unique=False, schema='explorer')
    # ### end Alembic commands ###
