"""suitability claims on experiences and venues

Adds the column that lets a constrained search mean something: what a listing
claims to be suitable for, over the vocabulary in `catalog/suitability.py`.

Empty rather than null for every existing row, and that is the correct backfill.
An empty set reads as "nobody has said", which is exactly true of a catalogue
published before there was anywhere to say it - whereas guessing from a title
would manufacture claims no publisher made and put them behind an allergy filter.

`venues.facilities` already existed with the right shape and was written empty by
every code path. It gains only the GIN index, because it is now queried by
containment alongside the new column.

Revision ID: 3b2ab5b920a3
Revises: b4a17c9e2f30
Create Date: 2026-08-18 12:35:30.695869
"""
from __future__ import annotations

from collections.abc import Sequence

# Custom column types autogenerate can emit. Imported unconditionally because the
# render hooks that would otherwise add them do not fire in every case - notably
# geoalchemy2 columns wrapped in sa.Computed.
import geoalchemy2  # noqa: F401
import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '3b2ab5b920a3'
down_revision: str | None = 'b4a17c9e2f30'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiences', sa.Column('suitability', postgresql.ARRAY(sa.String(length=64)), server_default='{}', nullable=False), schema='catalog')
    op.create_index('ix_experiences_suitability', 'experiences', ['suitability'], unique=False, schema='catalog', postgresql_using='gin')
    op.create_index('ix_venues_facilities', 'venues', ['facilities'], unique=False, schema='catalog', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_venues_facilities', table_name='venues', schema='catalog', postgresql_using='gin')
    op.drop_index('ix_experiences_suitability', table_name='experiences', schema='catalog', postgresql_using='gin')
    op.drop_column('experiences', 'suitability', schema='catalog')
    # ### end Alembic commands ###
