"""publisher reputation scores

Revision ID: 469c5f33dd3e
Revises: 9376844e4bdd
Create Date: 2026-08-09 23:13:24.911875
"""
from __future__ import annotations

from collections.abc import Sequence

# Custom column types autogenerate can emit. Imported unconditionally because the
# render hooks that would otherwise add them do not fire in every case - notably
# geoalchemy2 columns wrapped in sa.Computed.
import geoalchemy2  # noqa: F401
import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '469c5f33dd3e'
down_revision: str | None = '9376844e4bdd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Server defaults added by hand. Autogenerate emitted these as NOT NULL with
    # no default, which cannot be applied to a table that already has rows - the
    # migration would pass on an empty development database and fail on the one
    # that matters.
    #
    # 0.5 is neutral, not bad: every existing publisher starts unproven rather
    # than condemned, and the hourly job replaces it with a real figure on its
    # first run.
    op.add_column(
        'publishers',
        sa.Column(
            'reputation_score',
            sa.Numeric(precision=4, scale=3),
            nullable=False,
            server_default='0.5',
        ),
        schema='publisher',
    )
    op.add_column(
        'publishers',
        sa.Column(
            'reputation_signals',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        schema='publisher',
    )
    op.add_column(
        'publishers',
        sa.Column('reputation_computed_at', sa.DateTime(timezone=True), nullable=True),
        schema='publisher',
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publishers', 'reputation_computed_at', schema='publisher')
    op.drop_column('publishers', 'reputation_signals', schema='publisher')
    op.drop_column('publishers', 'reputation_score', schema='publisher')
    # ### end Alembic commands ###
