"""account type on the user

An account is a person **or** a business, never both. This is the column that
says which, and it is on the user rather than on something the user owns
because a business account has no personal profile behind it.

Every existing row becomes `individual` through the server default, which is
what they already were. `account_type_chosen_at` stays null for all of them, and
that is the point: it distinguishes "answered individual" from "never asked", so
the interface can prompt once instead of reading a default as a decision.

Revision ID: 4afd88bcbe06
Revises: 4ddcf2edae51
Create Date: 2026-08-19 17:27:37.290877
"""
from __future__ import annotations

from collections.abc import Sequence

# Custom column types autogenerate can emit. Imported unconditionally because the
# render hooks that would otherwise add them do not fire in every case - notably
# geoalchemy2 columns wrapped in sa.Computed.
import geoalchemy2  # noqa: F401
import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from alembic import op


revision: str = '4afd88bcbe06'
down_revision: str | None = '4ddcf2edae51'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_type', sa.String(length=16), server_default='individual', nullable=False), schema='identity')
    op.add_column('users', sa.Column('account_type_chosen_at', sa.DateTime(timezone=True), nullable=True), schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'account_type_chosen_at', schema='identity')
    op.drop_column('users', 'account_type', schema='identity')
    # ### end Alembic commands ###
