"""business profiles and publisher team membership

Two changes, one shape: a publisher can now describe itself as a business, and a
business can have staff.

`publishers` gains `business_type`, `cover_url` and `social`. All nullable or
defaulted, so every existing publisher is untouched and remains exactly what it
was - a person who posts. A personal publisher never has a business type, and
that is not missing data.

`publisher_members` is new. The owner is deliberately **not** a row in it:
ownership stays `publishers.owner_user_id`, which every authorization check
already keyed on, and a membership claiming to be the owner would be a second
answer to the same question. `user_id` is nullable because somebody can be
invited by email before they have an account.

No backfill. Existing publishers have no team, which is true.

Revision ID: 4ddcf2edae51
Revises: 3b2ab5b920a3
Create Date: 2026-08-19 12:06:56.520631
"""
from __future__ import annotations

from collections.abc import Sequence

# Custom column types autogenerate can emit. Imported unconditionally because the
# render hooks that would otherwise add them do not fire in every case - notably
# geoalchemy2 columns wrapped in sa.Computed.
import geoalchemy2  # noqa: F401
import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '4ddcf2edae51'
down_revision: str | None = '3b2ab5b920a3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publisher_members',
    sa.Column('publisher_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('invited_email', sa.String(length=320), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='invited', nullable=False),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['identity.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.publishers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publisher_id', 'user_id', name='uq_publisher_member'),
    schema='publisher'
    )
    op.create_index('ix_publisher_members_user', 'publisher_members', ['user_id', 'status'], unique=False, schema='publisher')
    op.create_index(op.f('ix_publisher_publisher_members_invited_email'), 'publisher_members', ['invited_email'], unique=False, schema='publisher')
    op.create_index(op.f('ix_publisher_publisher_members_publisher_id'), 'publisher_members', ['publisher_id'], unique=False, schema='publisher')
    op.create_index(op.f('ix_publisher_publisher_members_user_id'), 'publisher_members', ['user_id'], unique=False, schema='publisher')
    op.add_column('publishers', sa.Column('business_type', sa.String(length=40), nullable=True), schema='publisher')
    op.add_column('publishers', sa.Column('cover_url', sa.Text(), nullable=True), schema='publisher')
    op.add_column('publishers', sa.Column('social', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False), schema='publisher')
    op.create_index(op.f('ix_publisher_publishers_business_type'), 'publishers', ['business_type'], unique=False, schema='publisher')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publisher_publishers_business_type'), table_name='publishers', schema='publisher')
    op.drop_column('publishers', 'social', schema='publisher')
    op.drop_column('publishers', 'cover_url', schema='publisher')
    op.drop_column('publishers', 'business_type', schema='publisher')
    op.drop_index(op.f('ix_publisher_publisher_members_user_id'), table_name='publisher_members', schema='publisher')
    op.drop_index(op.f('ix_publisher_publisher_members_publisher_id'), table_name='publisher_members', schema='publisher')
    op.drop_index(op.f('ix_publisher_publisher_members_invited_email'), table_name='publisher_members', schema='publisher')
    op.drop_index('ix_publisher_members_user', table_name='publisher_members', schema='publisher')
    op.drop_table('publisher_members', schema='publisher')
    # ### end Alembic commands ###
