"""notifications

Revision ID: 59790d37425e
Revises: 434a8cf7666e
Create Date: 2026-08-07 22:27:25.548964
"""
from __future__ import annotations

from collections.abc import Sequence

# Custom column types autogenerate can emit. Imported unconditionally because the
# render hooks that would otherwise add them do not fire in every case - notably
# geoalchemy2 columns wrapped in sa.Computed.
import geoalchemy2  # noqa: F401
import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '59790d37425e'
down_revision: str | None = '434a8cf7666e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('subject_type', sa.String(length=32), nullable=True),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('deliver_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kind', 'subject_id', name='uq_notification_user_kind_subject'),
    schema='explorer'
    )
    op.create_index(op.f('ix_explorer_notifications_user_id'), 'notifications', ['user_id'], unique=False, schema='explorer')
    op.create_index('ix_notifications_delivery', 'notifications', ['status', 'deliver_at'], unique=False, schema='explorer')
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False, schema='explorer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_user_created', table_name='notifications', schema='explorer')
    op.drop_index('ix_notifications_delivery', table_name='notifications', schema='explorer')
    op.drop_index(op.f('ix_explorer_notifications_user_id'), table_name='notifications', schema='explorer')
    op.drop_table('notifications', schema='explorer')
    # ### end Alembic commands ###
