"""Take a commission on ticket sales and record what publishers are owed

Revision ID: 5af19d330ee8
Revises: c3357ff9beaf
Create Date: 2026-08-28 21:17:38.292640
"""
from __future__ import annotations

from collections.abc import Sequence

# Custom column types autogenerate can emit. Imported unconditionally because the
# render hooks that would otherwise add them do not fire in every case - notably
# geoalchemy2 columns wrapped in sa.Computed.
import geoalchemy2  # noqa: F401
import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from alembic import op


revision: str = '5af19d330ee8'
down_revision: str | None = 'c3357ff9beaf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payouts',
    sa.Column('publisher_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_minor', sa.BigInteger(), nullable=False),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_minor >= 0', name='ck_payout_total_not_negative'),
    sa.PrimaryKeyConstraint('id'),
    schema='commerce'
    )
    op.create_index('ix_payouts_publisher', 'payouts', ['publisher_id', 'created_at'], unique=False, schema='commerce')
    op.create_table('ledger_entries',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('publisher_id', sa.UUID(), nullable=False),
    sa.Column('gross_minor', sa.BigInteger(), nullable=False),
    sa.Column('fee_minor', sa.BigInteger(), nullable=False),
    sa.Column('net_minor', sa.BigInteger(), nullable=False),
    sa.Column('fee_rate_bps', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payout_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fee_minor + net_minor = gross_minor', name='ck_ledger_balances'),
    sa.CheckConstraint('gross_minor >= 0 AND fee_minor >= 0 AND net_minor >= 0', name='ck_ledger_amounts_not_negative'),
    sa.ForeignKeyConstraint(['order_id'], ['commerce.orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payout_id'], ['commerce.payouts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', name='uq_ledger_entry_order'),
    schema='commerce'
    )
    op.create_index('ix_ledger_entries_unpaid', 'ledger_entries', ['publisher_id', 'currency'], unique=False, schema='commerce', postgresql_where='payout_id IS NULL')
    op.add_column('orders', sa.Column('publisher_id', sa.UUID(), nullable=True), schema='commerce')
    # A server default only so the existing rows have a value; dropped
    # immediately afterwards, because the application supplies it on every
    # insert and a default left in place would drift from the model and have
    # autogenerate proposing to remove it on every run.
    op.add_column(
        'orders',
        sa.Column('fee_rate_bps', sa.Integer(), nullable=False, server_default='0'),
        schema='commerce',
    )
    op.add_column(
        'orders',
        sa.Column('platform_fee_minor', sa.BigInteger(), nullable=False, server_default='0'),
        schema='commerce',
    )
    op.alter_column('orders', 'fee_rate_bps', server_default=None, schema='commerce')
    op.alter_column('orders', 'platform_fee_minor', server_default=None, schema='commerce')
    op.create_index(op.f('ix_commerce_orders_publisher_id'), 'orders', ['publisher_id'], unique=False, schema='commerce')
    op.create_check_constraint('ck_order_fee_within_amount', 'orders', 'platform_fee_minor >= 0 AND platform_fee_minor <= amount_minor', schema='commerce')
    op.add_column('publishers', sa.Column('fee_bps', sa.Integer(), nullable=True), schema='publisher')

    # Orders that were already sold. They have a publisher - it just was not
    # written down - and the money for them is sitting in Mado's account like
    # every other sale.
    op.execute(
        """
        UPDATE commerce.orders AS o
           SET publisher_id = e.publisher_id
          FROM catalog.experiences AS e
         WHERE e.id = o.experience_id
           AND o.publisher_id IS NULL
        """
    )

    # And the debt for them, at zero commission. Two decisions, both deliberate:
    #
    # The entries exist, because Mado is holding that money and owes it. A
    # ledger that begins at zero would quietly write off every sale made before
    # today, and the publisher would have no record of a payment that never
    # came.
    #
    # The fee is zero, because a commission cannot be charged backwards. Nobody
    # agreed to it when those tickets were sold, and applying today's rate to
    # them would take money out of a figure a publisher was already given.
    op.execute(
        """
        INSERT INTO commerce.ledger_entries
            (order_id, publisher_id, gross_minor, fee_minor, net_minor,
             fee_rate_bps, currency, earned_at)
        SELECT o.id, o.publisher_id, o.amount_minor, 0, o.amount_minor,
               0, o.currency, COALESCE(o.paid_at, o.created_at)
          FROM commerce.orders AS o
         WHERE o.status = 'paid'
           AND o.amount_minor > 0
           AND o.publisher_id IS NOT NULL
        ON CONFLICT (order_id) DO NOTHING
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publishers', 'fee_bps', schema='publisher')
    op.drop_constraint('ck_order_fee_within_amount', 'orders', schema='commerce', type_='check')
    op.drop_index(op.f('ix_commerce_orders_publisher_id'), table_name='orders', schema='commerce')
    op.drop_column('orders', 'platform_fee_minor', schema='commerce')
    op.drop_column('orders', 'fee_rate_bps', schema='commerce')
    op.drop_column('orders', 'publisher_id', schema='commerce')
    op.drop_index('ix_ledger_entries_unpaid', table_name='ledger_entries', schema='commerce', postgresql_where='payout_id IS NULL')
    op.drop_table('ledger_entries', schema='commerce')
    op.drop_index('ix_payouts_publisher', table_name='payouts', schema='commerce')
    op.drop_table('payouts', schema='commerce')
    # ### end Alembic commands ###
