"""ticketing, orders and payments

Revision ID: 5db5fc089dfa
Revises: 469c5f33dd3e
Create Date: 2026-08-11 13:13:10.832614
"""
from __future__ import annotations

from collections.abc import Sequence

# Custom column types autogenerate can emit. Imported unconditionally because the
# render hooks that would otherwise add them do not fire in every case - notably
# geoalchemy2 columns wrapped in sa.Computed.
import geoalchemy2  # noqa: F401
import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '5db5fc089dfa'
down_revision: str | None = '469c5f33dd3e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Autogenerate never emits this: it compares tables, and the schema they
    # live in has to exist before the first CREATE TABLE names it.
    op.execute("CREATE SCHEMA IF NOT EXISTS commerce")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_types',
    sa.Column('event_instance_id', sa.UUID(), nullable=False),
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('price_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('sold', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sales_open_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sales_close_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price_minor >= 0', name='ck_ticket_type_price_not_negative'),
    sa.CheckConstraint('quantity IS NULL OR quantity >= 0', name='ck_ticket_type_quantity'),
    sa.PrimaryKeyConstraint('id'),
    schema='commerce'
    )
    op.create_index('ix_ticket_types_occurrence', 'ticket_types', ['event_instance_id', 'position'], unique=False, schema='commerce')
    op.create_table('orders',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_instance_id', sa.UUID(), nullable=False),
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('experience_title', sa.String(length=300), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('provider_reference', sa.String(length=120), nullable=True),
    sa.Column('checkout_url', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_reason', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_minor >= 0', name='ck_order_amount_not_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference', name='uq_order_reference'),
    schema='commerce'
    )
    op.create_index(op.f('ix_commerce_orders_user_id'), 'orders', ['user_id'], unique=False, schema='commerce')
    op.create_index('ix_orders_occurrence', 'orders', ['event_instance_id'], unique=False, schema='commerce')
    op.create_index('ix_orders_pending_expiry', 'orders', ['expires_at'], unique=False, schema='commerce', postgresql_where="status = 'pending'")
    op.create_index('ix_orders_user_created', 'orders', ['user_id', 'created_at'], unique=False, schema='commerce')
    op.create_table('order_lines',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('ticket_type_id', sa.UUID(), nullable=False),
    sa.Column('ticket_type_name', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_minor', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_order_line_quantity_positive'),
    sa.ForeignKeyConstraint(['order_id'], ['commerce.orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='commerce'
    )
    op.create_index(op.f('ix_commerce_order_lines_order_id'), 'order_lines', ['order_id'], unique=False, schema='commerce')
    op.create_table('payment_events',
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['commerce.orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_payment_event_external'),
    schema='commerce'
    )
    op.create_table('tickets',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_instance_id', sa.UUID(), nullable=False),
    sa.Column('ticket_type_id', sa.UUID(), nullable=False),
    sa.Column('ticket_type_name', sa.String(length=80), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['commerce.orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_ticket_code'),
    schema='commerce'
    )
    op.create_index(op.f('ix_commerce_tickets_order_id'), 'tickets', ['order_id'], unique=False, schema='commerce')
    op.create_index(op.f('ix_commerce_tickets_user_id'), 'tickets', ['user_id'], unique=False, schema='commerce')
    op.create_index('ix_tickets_occurrence', 'tickets', ['event_instance_id', 'status'], unique=False, schema='commerce')
    op.add_column('experiences', sa.Column('external_ticket_url', sa.Text(), nullable=True), schema='catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiences', 'external_ticket_url', schema='catalog')
    op.drop_index('ix_tickets_occurrence', table_name='tickets', schema='commerce')
    op.drop_index(op.f('ix_commerce_tickets_user_id'), table_name='tickets', schema='commerce')
    op.drop_index(op.f('ix_commerce_tickets_order_id'), table_name='tickets', schema='commerce')
    op.drop_table('tickets', schema='commerce')
    op.drop_table('payment_events', schema='commerce')
    op.drop_index(op.f('ix_commerce_order_lines_order_id'), table_name='order_lines', schema='commerce')
    op.drop_table('order_lines', schema='commerce')
    op.drop_index('ix_orders_user_created', table_name='orders', schema='commerce')
    op.drop_index('ix_orders_pending_expiry', table_name='orders', schema='commerce', postgresql_where="status = 'pending'")
    op.drop_index('ix_orders_occurrence', table_name='orders', schema='commerce')
    op.drop_index(op.f('ix_commerce_orders_user_id'), table_name='orders', schema='commerce')
    op.drop_table('orders', schema='commerce')
    op.drop_index('ix_ticket_types_occurrence', table_name='ticket_types', schema='commerce')
    op.drop_table('ticket_types', schema='commerce')
    # ### end Alembic commands ###

    # Left behind deliberately if anything is still in it. Dropping a schema
    # that holds financial records because a migration ran backwards is not a
    # rollback, it is data loss - RESTRICT makes the failure loud instead.
    op.execute("DROP SCHEMA IF EXISTS commerce RESTRICT")
