"""open publishing: personal publishers, moderation, reports

Revision ID: 5de99a5177bd
Revises: c2e9b69014ef
Create Date: 2026-08-06 07:06:35.456466
"""
from __future__ import annotations

from collections.abc import Sequence

# Custom column types autogenerate can emit. Imported unconditionally because the
# render hooks that would otherwise add them do not fire in every case - notably
# geoalchemy2 columns wrapped in sa.Computed.
import geoalchemy2  # noqa: F401
import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from alembic import op


revision: str = '5de99a5177bd'
down_revision: str | None = 'c2e9b69014ef'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Existing publishers predate the individual/organization distinction and were
    # all seeded as museums, hotels and universities - they are organizations.
    # Applied first so no two rows collide on the new (owner_user_id, type)
    # unique constraint via the 'individual' default.
    op.execute(
        "UPDATE publisher.publishers SET type = 'organization' WHERE type = 'publisher'"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_reports',
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('reporter_user_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['catalog.experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['identity.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['identity.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reporter_user_id', 'experience_id', name='uq_report_per_reporter'),
    schema='explorer'
    )
    op.create_index(op.f('ix_explorer_content_reports_experience_id'), 'content_reports', ['experience_id'], unique=False, schema='explorer')
    op.create_index(op.f('ix_explorer_content_reports_reporter_user_id'), 'content_reports', ['reporter_user_id'], unique=False, schema='explorer')
    op.create_index('ix_reports_status_created', 'content_reports', ['status', 'created_at'], unique=False, schema='explorer')
    op.add_column('experiences', sa.Column('moderation_status', sa.String(length=16), server_default='approved', nullable=False), schema='catalog')
    op.add_column('experiences', sa.Column('moderation_notes', sa.Text(), nullable=True), schema='catalog')
    op.add_column('experiences', sa.Column('report_count', sa.Integer(), server_default='0', nullable=False), schema='catalog')
    op.add_column('experiences', sa.Column('risk_score', sa.Numeric(precision=4, scale=3), server_default='0', nullable=False), schema='catalog')
    op.add_column('experiences', sa.Column('moderation_locked', sa.Boolean(), server_default='false', nullable=False), schema='catalog')
    op.create_index(op.f('ix_publisher_publishers_owner_user_id'), 'publishers', ['owner_user_id'], unique=False, schema='publisher')
    op.create_unique_constraint('uq_personal_publisher_per_user', 'publishers', ['owner_user_id', 'type'], schema='publisher')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_personal_publisher_per_user', 'publishers', schema='publisher', type_='unique')
    op.drop_index(op.f('ix_publisher_publishers_owner_user_id'), table_name='publishers', schema='publisher')
    op.drop_column('experiences', 'moderation_locked', schema='catalog')
    op.drop_column('experiences', 'risk_score', schema='catalog')
    op.drop_column('experiences', 'report_count', schema='catalog')
    op.drop_column('experiences', 'moderation_notes', schema='catalog')
    op.drop_column('experiences', 'moderation_status', schema='catalog')
    op.drop_index('ix_reports_status_created', table_name='content_reports', schema='explorer')
    op.drop_index(op.f('ix_explorer_content_reports_reporter_user_id'), table_name='content_reports', schema='explorer')
    op.drop_index(op.f('ix_explorer_content_reports_experience_id'), table_name='content_reports', schema='explorer')
    op.drop_table('content_reports', schema='explorer')
    # ### end Alembic commands ###
