"""itineraries and stops

Revision ID: 7bacd650b168
Revises: 8963c8f0365d
Create Date: 2026-08-06 11:31:07.113400
"""
from __future__ import annotations

from collections.abc import Sequence

# Custom column types autogenerate can emit. Imported unconditionally because the
# render hooks that would otherwise add them do not fire in every case - notably
# geoalchemy2 columns wrapped in sa.Computed.
import geoalchemy2  # noqa: F401
import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '7bacd650b168'
down_revision: str | None = '8963c8f0365d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itineraries',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('anonymous_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('city_slug', sa.String(length=120), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_travel_minutes', sa.Integer(), nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='explorer'
    )
    op.create_index(op.f('ix_explorer_itineraries_anonymous_id'), 'itineraries', ['anonymous_id'], unique=False, schema='explorer')
    op.create_index(op.f('ix_explorer_itineraries_user_id'), 'itineraries', ['user_id'], unique=False, schema='explorer')
    op.create_index('ix_itineraries_user_created', 'itineraries', ['user_id', 'created_at'], unique=False, schema='explorer')
    op.create_table('itinerary_stops',
    sa.Column('itinerary_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('event_instance_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('arrive_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('depart_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('travel_minutes', sa.Integer(), nullable=False),
    sa.Column('travel_km', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_fixed_time', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['explorer.itineraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('itinerary_id', 'position', name='uq_itinerary_stop_position'),
    schema='explorer'
    )
    op.create_index(op.f('ix_explorer_itinerary_stops_itinerary_id'), 'itinerary_stops', ['itinerary_id'], unique=False, schema='explorer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_explorer_itinerary_stops_itinerary_id'), table_name='itinerary_stops', schema='explorer')
    op.drop_table('itinerary_stops', schema='explorer')
    op.drop_index('ix_itineraries_user_created', table_name='itineraries', schema='explorer')
    op.drop_index(op.f('ix_explorer_itineraries_user_id'), table_name='itineraries', schema='explorer')
    op.drop_index(op.f('ix_explorer_itineraries_anonymous_id'), table_name='itineraries', schema='explorer')
    op.drop_table('itineraries', schema='explorer')
    # ### end Alembic commands ###
