"""Keep a plan being bought apart from the plan in force

Revision ID: 9b322ae2a55e
Revises: 59d02736e2e2
Create Date: 2026-08-28 22:35:17.402132
"""
from __future__ import annotations

from collections.abc import Sequence

# Custom column types autogenerate can emit. Imported unconditionally because the
# render hooks that would otherwise add them do not fire in every case - notably
# geoalchemy2 columns wrapped in sa.Computed.
import geoalchemy2  # noqa: F401
import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from alembic import op


revision: str = '9b322ae2a55e'
down_revision: str | None = '59d02736e2e2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('pending_plan', sa.String(length=32), nullable=True), schema='publisher')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'pending_plan', schema='publisher')
    # ### end Alembic commands ###
