"""Sell one labelled slot in discovery without touching the ranking

Revision ID: c0ded3bfd337
Revises: 6dfd0e057bbb
Create Date: 2026-08-28 23:28:10.603346
"""
from __future__ import annotations

from collections.abc import Sequence

# Custom column types autogenerate can emit. Imported unconditionally because the
# render hooks that would otherwise add them do not fire in every case - notably
# geoalchemy2 columns wrapped in sa.Computed.
import geoalchemy2  # noqa: F401
import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from alembic import op


revision: str = 'c0ded3bfd337'
down_revision: str | None = '6dfd0e057bbb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # The domain's own schema, which autogenerate does not create - it compares
    # tables within schemas it is told about (`MADO_SCHEMAS` in env.py) and
    # assumes they exist.
    op.execute("CREATE SCHEMA IF NOT EXISTS promotion")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('publisher_id', sa.UUID(), nullable=False),
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('city_slug', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('radius_km', sa.Float(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('provider_reference', sa.String(length=120), nullable=True),
    sa.Column('checkout_url', sa.String(length=1000), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_reason', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_minor >= 0', name='ck_promotion_amount_not_negative'),
    sa.CheckConstraint('ends_at > starts_at', name='ck_promotion_runs_forwards'),
    sa.CheckConstraint('radius_km IS NULL OR radius_km > 0', name='ck_promotion_radius_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference', name='uq_promotion_reference'),
    schema='promotion'
    )
    op.create_index(op.f('ix_promotion_promotions_city_slug'), 'promotions', ['city_slug'], unique=False, schema='promotion')
    op.create_index('ix_promotions_publisher', 'promotions', ['publisher_id', 'created_at'], unique=False, schema='promotion')
    op.create_index('ix_promotions_running', 'promotions', ['starts_at', 'ends_at'], unique=False, schema='promotion', postgresql_where="status = 'active'")
    op.create_table('promotion_days',
    sa.Column('promotion_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotion.promotions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promotion_id', 'day', name='uq_promotion_day'),
    schema='promotion'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promotion_days', schema='promotion')
    op.drop_index('ix_promotions_running', table_name='promotions', schema='promotion', postgresql_where="status = 'active'")
    op.drop_index('ix_promotions_publisher', table_name='promotions', schema='promotion')
    op.drop_index(op.f('ix_promotion_promotions_city_slug'), table_name='promotions', schema='promotion')
    op.drop_table('promotions', schema='promotion')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS promotion")
