"""initial platform schema

Revision ID: c2e9b69014ef
Revises: 
Create Date: 2026-08-05 23:21:17.229190
"""
from __future__ import annotations

from collections.abc import Sequence

# Custom column types autogenerate can emit. Imported unconditionally because the
# render hooks that would otherwise add them do not fire in every case - notably
# geoalchemy2 columns wrapped in sa.Computed.
import geoalchemy2  # noqa: F401
import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'c2e9b69014ef'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['catalog.categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_categories_slug'), 'categories', ['slug'], unique=True, schema='catalog')
    op.create_table('cities',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('languages', postgresql.ARRAY(sa.String(length=12)), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_cities_slug'), 'cities', ['slug'], unique=True, schema='catalog')
    op.create_table('tags',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_tags_slug'), 'tags', ['slug'], unique=True, schema='catalog')
    op.create_table('interaction_events',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('anonymous_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='explorer'
    )
    op.create_index(op.f('ix_explorer_interaction_events_anonymous_id'), 'interaction_events', ['anonymous_id'], unique=False, schema='explorer')
    op.create_index(op.f('ix_explorer_interaction_events_occurred_at'), 'interaction_events', ['occurred_at'], unique=False, schema='explorer')
    op.create_index(op.f('ix_explorer_interaction_events_user_id'), 'interaction_events', ['user_id'], unique=False, schema='explorer')
    op.create_index('ix_interaction_user_time', 'interaction_events', ['user_id', 'occurred_at'], unique=False, schema='explorer')
    op.create_table('users',
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_table('conversations',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('anonymous_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('city_slug', sa.String(length=120), nullable=True),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_index(op.f('ix_ai_conversations_anonymous_id'), 'conversations', ['anonymous_id'], unique=False, schema='ai')
    op.create_index(op.f('ix_ai_conversations_user_id'), 'conversations', ['user_id'], unique=False, schema='ai')
    op.create_index('ix_conversations_user_updated', 'conversations', ['user_id', 'updated_at'], unique=False, schema='ai')
    op.create_table('user_memories',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('attribute', sa.String(length=64), nullable=True),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('source', sa.String(length=48), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('last_reinforced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_index(op.f('ix_ai_user_memories_user_id'), 'user_memories', ['user_id'], unique=False, schema='ai')
    op.create_index('ix_user_memories_user_category', 'user_memories', ['user_id', 'category'], unique=False, schema='ai')
    op.create_table('neighborhoods',
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['catalog.cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'slug', name='uq_neighborhood_city_slug'),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_neighborhoods_city_id'), 'neighborhoods', ['city_id'], unique=False, schema='catalog')
    op.create_table('saved_items',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entity_type', 'entity_id', name='uq_saved_item'),
    schema='explorer'
    )
    op.create_index(op.f('ix_explorer_saved_items_user_id'), 'saved_items', ['user_id'], unique=False, schema='explorer')
    op.create_index('ix_saved_items_user', 'saved_items', ['user_id', 'created_at'], unique=False, schema='explorer')
    op.create_table('auth_identities',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_id', name='uq_auth_identity_provider'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_auth_identities_user_id'), 'auth_identities', ['user_id'], unique=False, schema='identity')
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('device', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash'),
    schema='identity'
    )
    op.create_index('ix_sessions_user_active', 'sessions', ['user_id', 'revoked_at'], unique=False, schema='identity')
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=12), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('home_city_slug', sa.String(length=120), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('privacy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_user_profiles_email'), 'user_profiles', ['email'], unique=False, schema='identity')
    op.create_table('publishers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=80), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('trust_level', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('contact', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['identity.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='publisher'
    )
    op.create_index(op.f('ix_publisher_publishers_slug'), 'publishers', ['slug'], unique=True, schema='publisher')
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=48), nullable=True),
    sa.Column('intent_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('referenced_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai.conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'messages', ['conversation_id'], unique=False, schema='ai')
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False, schema='ai')
    op.create_table('venues',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('publisher_id', sa.UUID(), nullable=True),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('neighborhood_id', sa.UUID(), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geo', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), sa.Computed('ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography', persisted=True), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('facilities', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('accessibility', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('opening_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contact', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['catalog.cities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['neighborhood_id'], ['catalog.neighborhoods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.publishers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_venues_city_id'), 'venues', ['city_id'], unique=False, schema='catalog')
    op.create_index(op.f('ix_catalog_venues_neighborhood_id'), 'venues', ['neighborhood_id'], unique=False, schema='catalog')
    op.create_index(op.f('ix_catalog_venues_publisher_id'), 'venues', ['publisher_id'], unique=False, schema='catalog')
    op.create_index(op.f('ix_catalog_venues_slug'), 'venues', ['slug'], unique=True, schema='catalog')
    op.create_index('ix_venues_geo', 'venues', ['geo'], unique=False, schema='catalog', postgresql_using='gist')
    op.create_table('experiences',
    sa.Column('publisher_id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=True),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('slug', sa.String(length=260), nullable=False),
    sa.Column('summary', sa.String(length=400), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_type', sa.String(length=16), nullable=False),
    sa.Column('price_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_indoor', sa.Boolean(), nullable=True),
    sa.Column('accessibility', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('popularity_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('trend_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('rating_average', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['catalog.categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['city_id'], ['catalog.cities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.publishers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['catalog.venues.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_experiences_category_id'), 'experiences', ['category_id'], unique=False, schema='catalog')
    op.create_index(op.f('ix_catalog_experiences_city_id'), 'experiences', ['city_id'], unique=False, schema='catalog')
    op.create_index(op.f('ix_catalog_experiences_publisher_id'), 'experiences', ['publisher_id'], unique=False, schema='catalog')
    op.create_index(op.f('ix_catalog_experiences_slug'), 'experiences', ['slug'], unique=True, schema='catalog')
    op.create_index(op.f('ix_catalog_experiences_venue_id'), 'experiences', ['venue_id'], unique=False, schema='catalog')
    op.create_index('ix_experiences_city_status', 'experiences', ['city_id', 'status'], unique=False, schema='catalog')
    op.create_index('ix_experiences_status_type', 'experiences', ['status', 'type'], unique=False, schema='catalog')
    op.create_table('event_instances',
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('remaining', sa.Integer(), nullable=True),
    sa.Column('rescheduled_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['catalog.experiences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_event_instances_experience_id'), 'event_instances', ['experience_id'], unique=False, schema='catalog')
    op.create_index('ix_event_instances_experience_start', 'event_instances', ['experience_id', 'start_time'], unique=False, schema='catalog')
    op.create_index('ix_event_instances_start', 'event_instances', ['start_time'], unique=False, schema='catalog')
    op.create_table('experience_tags',
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['catalog.experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['catalog.tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('experience_id', 'tag_id'),
    schema='catalog'
    )
    op.create_table('media',
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('alt_text', sa.String(length=400), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['catalog.experiences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_media_experience_id'), 'media', ['experience_id'], unique=False, schema='catalog')
    op.create_table('reviews',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('verified_attendance', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['experience_id'], ['catalog.experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'experience_id', name='uq_review_user_experience'),
    schema='explorer'
    )
    op.create_index(op.f('ix_explorer_reviews_experience_id'), 'reviews', ['experience_id'], unique=False, schema='explorer')
    op.create_index(op.f('ix_explorer_reviews_user_id'), 'reviews', ['user_id'], unique=False, schema='explorer')
    op.create_index('ix_reviews_experience_status', 'reviews', ['experience_id', 'status'], unique=False, schema='explorer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_experience_status', table_name='reviews', schema='explorer')
    op.drop_index(op.f('ix_explorer_reviews_user_id'), table_name='reviews', schema='explorer')
    op.drop_index(op.f('ix_explorer_reviews_experience_id'), table_name='reviews', schema='explorer')
    op.drop_table('reviews', schema='explorer')
    op.drop_index(op.f('ix_catalog_media_experience_id'), table_name='media', schema='catalog')
    op.drop_table('media', schema='catalog')
    op.drop_table('experience_tags', schema='catalog')
    op.drop_index('ix_event_instances_start', table_name='event_instances', schema='catalog')
    op.drop_index('ix_event_instances_experience_start', table_name='event_instances', schema='catalog')
    op.drop_index(op.f('ix_catalog_event_instances_experience_id'), table_name='event_instances', schema='catalog')
    op.drop_table('event_instances', schema='catalog')
    op.drop_index('ix_experiences_status_type', table_name='experiences', schema='catalog')
    op.drop_index('ix_experiences_city_status', table_name='experiences', schema='catalog')
    op.drop_index(op.f('ix_catalog_experiences_venue_id'), table_name='experiences', schema='catalog')
    op.drop_index(op.f('ix_catalog_experiences_slug'), table_name='experiences', schema='catalog')
    op.drop_index(op.f('ix_catalog_experiences_publisher_id'), table_name='experiences', schema='catalog')
    op.drop_index(op.f('ix_catalog_experiences_city_id'), table_name='experiences', schema='catalog')
    op.drop_index(op.f('ix_catalog_experiences_category_id'), table_name='experiences', schema='catalog')
    op.drop_table('experiences', schema='catalog')
    op.drop_index('ix_venues_geo', table_name='venues', schema='catalog', postgresql_using='gist')
    op.drop_index(op.f('ix_catalog_venues_slug'), table_name='venues', schema='catalog')
    op.drop_index(op.f('ix_catalog_venues_publisher_id'), table_name='venues', schema='catalog')
    op.drop_index(op.f('ix_catalog_venues_neighborhood_id'), table_name='venues', schema='catalog')
    op.drop_index(op.f('ix_catalog_venues_city_id'), table_name='venues', schema='catalog')
    op.drop_table('venues', schema='catalog')
    op.drop_index('ix_messages_conversation_created', table_name='messages', schema='ai')
    op.drop_index(op.f('ix_ai_messages_conversation_id'), table_name='messages', schema='ai')
    op.drop_table('messages', schema='ai')
    op.drop_index(op.f('ix_publisher_publishers_slug'), table_name='publishers', schema='publisher')
    op.drop_table('publishers', schema='publisher')
    op.drop_index(op.f('ix_identity_user_profiles_email'), table_name='user_profiles', schema='identity')
    op.drop_table('user_profiles', schema='identity')
    op.drop_index('ix_sessions_user_active', table_name='sessions', schema='identity')
    op.drop_table('sessions', schema='identity')
    op.drop_index(op.f('ix_identity_auth_identities_user_id'), table_name='auth_identities', schema='identity')
    op.drop_table('auth_identities', schema='identity')
    op.drop_index('ix_saved_items_user', table_name='saved_items', schema='explorer')
    op.drop_index(op.f('ix_explorer_saved_items_user_id'), table_name='saved_items', schema='explorer')
    op.drop_table('saved_items', schema='explorer')
    op.drop_index(op.f('ix_catalog_neighborhoods_city_id'), table_name='neighborhoods', schema='catalog')
    op.drop_table('neighborhoods', schema='catalog')
    op.drop_index('ix_user_memories_user_category', table_name='user_memories', schema='ai')
    op.drop_index(op.f('ix_ai_user_memories_user_id'), table_name='user_memories', schema='ai')
    op.drop_table('user_memories', schema='ai')
    op.drop_index('ix_conversations_user_updated', table_name='conversations', schema='ai')
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='conversations', schema='ai')
    op.drop_index(op.f('ix_ai_conversations_anonymous_id'), table_name='conversations', schema='ai')
    op.drop_table('conversations', schema='ai')
    op.drop_table('users', schema='identity')
    op.drop_index('ix_interaction_user_time', table_name='interaction_events', schema='explorer')
    op.drop_index(op.f('ix_explorer_interaction_events_user_id'), table_name='interaction_events', schema='explorer')
    op.drop_index(op.f('ix_explorer_interaction_events_occurred_at'), table_name='interaction_events', schema='explorer')
    op.drop_index(op.f('ix_explorer_interaction_events_anonymous_id'), table_name='interaction_events', schema='explorer')
    op.drop_table('interaction_events', schema='explorer')
    op.drop_index(op.f('ix_catalog_tags_slug'), table_name='tags', schema='catalog')
    op.drop_table('tags', schema='catalog')
    op.drop_index(op.f('ix_catalog_cities_slug'), table_name='cities', schema='catalog')
    op.drop_table('cities', schema='catalog')
    op.drop_index(op.f('ix_catalog_categories_slug'), table_name='categories', schema='catalog')
    op.drop_table('categories', schema='catalog')
    # ### end Alembic commands ###
