"""a business gallery of photos and videos

A business can now show pictures of itself, not only of what is on. `catalog.media`
could not hold them: a row there requires an experience id, so a lobby photograph
would have needed a hidden listing to hang off - and that listing would then have
to be excluded by hand from search, ranking, the feed and every count. One more
table is cheaper than a phantom row everything else has to remember to ignore.

`kind` is `image` or `video` rather than two tables, because they sit in one grid
in one order and splitting them would mean merging two sequences on every read.
`width`/`height` are nullable and null for video: nothing here decodes video, and
recording a guessed aspect ratio would make the client reserve the wrong space.

Additive only. Nothing existing is touched and there is no backfill - businesses
have empty galleries, which is true.

Revision ID: c3357ff9beaf
Revises: 2b52eb5c077a
Create Date: 2026-08-21 16:13:03.967247
"""
from __future__ import annotations

from collections.abc import Sequence

# Custom column types autogenerate can emit. Imported unconditionally because the
# render hooks that would otherwise add them do not fire in every case - notably
# geoalchemy2 columns wrapped in sa.Computed.
import geoalchemy2  # noqa: F401
import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from alembic import op


revision: str = 'c3357ff9beaf'
down_revision: str | None = '2b52eb5c077a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_items',
    sa.Column('publisher_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('caption', sa.String(length=400), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.publishers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='publisher'
    )
    # Only the composite. Every read is "this business's gallery, in order", and
    # it leads with publisher_id, so a second index on that column alone would be
    # the same prefix written twice on insert and read by nothing.
    op.create_index('ix_gallery_items_publisher_order', 'gallery_items', ['publisher_id', 'sort_order'], unique=False, schema='publisher')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gallery_items_publisher_order', table_name='gallery_items', schema='publisher')
    op.drop_table('gallery_items', schema='publisher')
    # ### end Alembic commands ###
