"""feature flags and audit log

Revision ID: cb0b497b76ac
Revises: ea3c4da54c76
Create Date: 2026-08-08 23:54:13.278774
"""
from __future__ import annotations

from collections.abc import Sequence

# Custom column types autogenerate can emit. Imported unconditionally because the
# render hooks that would otherwise add them do not fire in every case - notably
# geoalchemy2 columns wrapped in sa.Computed.
import geoalchemy2  # noqa: F401
import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'cb0b497b76ac'
down_revision: str | None = 'ea3c4da54c76'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('rollout_percentage', sa.Integer(), nullable=False),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_feature_flags_key'), 'feature_flags', ['key'], unique=True, schema='identity')
    op.create_table('audit_entries',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_label', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('subject_label', sa.String(length=300), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['identity.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_index('ix_audit_actor', 'audit_entries', ['actor_user_id', 'occurred_at'], unique=False, schema='identity')
    op.create_index('ix_audit_occurred', 'audit_entries', ['occurred_at'], unique=False, schema='identity')
    op.create_index('ix_audit_subject', 'audit_entries', ['subject_id', 'occurred_at'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_audit_entries_action'), 'audit_entries', ['action'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_audit_entries_occurred_at'), 'audit_entries', ['occurred_at'], unique=False, schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identity_audit_entries_occurred_at'), table_name='audit_entries', schema='identity')
    op.drop_index(op.f('ix_identity_audit_entries_action'), table_name='audit_entries', schema='identity')
    op.drop_index('ix_audit_subject', table_name='audit_entries', schema='identity')
    op.drop_index('ix_audit_occurred', table_name='audit_entries', schema='identity')
    op.drop_index('ix_audit_actor', table_name='audit_entries', schema='identity')
    op.drop_table('audit_entries', schema='identity')
    op.drop_index(op.f('ix_identity_feature_flags_key'), table_name='feature_flags', schema='identity')
    op.drop_table('feature_flags', schema='identity')
    # ### end Alembic commands ###
