"""reservations

Revision ID: ea3c4da54c76
Revises: 27fa1e8ac939
Create Date: 2026-08-08 23:28:54.165807
"""
from __future__ import annotations

from collections.abc import Sequence

# Custom column types autogenerate can emit. Imported unconditionally because the
# render hooks that would otherwise add them do not fire in every case - notably
# geoalchemy2 columns wrapped in sa.Computed.
import geoalchemy2  # noqa: F401
import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from alembic import op


revision: str = 'ea3c4da54c76'
down_revision: str | None = '27fa1e8ac939'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_instance_id', sa.UUID(), nullable=False),
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('experience_title', sa.String(length=300), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='confirmed', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_instance_id', name='uq_reservation_user_occurrence'),
    schema='explorer'
    )
    op.create_index(op.f('ix_explorer_reservations_user_id'), 'reservations', ['user_id'], unique=False, schema='explorer')
    op.create_index('ix_reservations_occurrence', 'reservations', ['event_instance_id', 'status'], unique=False, schema='explorer')
    op.create_index('ix_reservations_user', 'reservations', ['user_id', 'created_at'], unique=False, schema='explorer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reservations_user', table_name='reservations', schema='explorer')
    op.drop_index('ix_reservations_occurrence', table_name='reservations', schema='explorer')
    op.drop_index(op.f('ix_explorer_reservations_user_id'), table_name='reservations', schema='explorer')
    op.drop_table('reservations', schema='explorer')
    # ### end Alembic commands ###
